version: "3.1"

networks:
  tiseu:
    name: tiseu

x-auth-base-service: &auth-base-service
  build:
    context: ./auth-server/
    dockerfile: Dockerfile.prod
  working_dir: /usr/src/app
  environment:
    - NODE_ENV=docker-development
    - DB_NAME=auth-server
    - DB_URI=mongodb://auth-mongo:27017
    - JWT_SECRET=secret
    - JWT_DURATION=120m

x-auth-direct-run-service: &auth-direct-run-service
  <<: *auth-base-service
  profiles: ["direct-run"]
  build:
    context: ./auth-server/
    dockerfile: Dockerfile.dev

services:
  # --- AUTH SERVER ---
  auth-app:
    <<: *auth-base-service
    command: node dist/main.js
    container_name: auth-app
    networks:
      tiseu:
        aliases:
          - auth-app
    depends_on:
      - auth-mongo
    ports:
      - "4101:3101"
      - "5101:3101"

  auth-mongo:
    image: mongo
    container_name: auth-mongo
    ports:
      - "4117:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/db --quiet
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s
    volumes:
      - auth-mongodb:/data/db
    networks:
      tiseu:
        aliases:
          - auth-mongo

  auth-seed-admin:
    <<: *auth-direct-run-service
    entrypoint: npx nestjs-command seed:admin
    networks:
      tiseu:
        aliases:
          - auth-command-seed-admin
  auth-seed-user:
    <<: *auth-direct-run-service
    entrypoint: npx nestjs-command seed:user
    networks:
      tiseu:
        aliases:
          - auth-command-seed-user

  # --- ePortal ---
  eportal:
    environment:
      - VITE_PORT=4011
      - VITE_APP_URL=http://localhost:4011
      - VITE_AUTH_SERVER_URL=http://localhost:4101
    build:
      context: ./eportal/
    container_name: eportal
    networks:
      tiseu:
        aliases:
          - eportal
    ports:
      - "4011:4011"

  # --- Mup licna dokumenta ---
  mup-licna-dokumenta-frontend:
    environment:
      - PORT=3000
      - APP_URL=http://localhost:3000
      - AUTH_SERVER_URL=http://localhost:5101
      - BACKEND_URL=http://localhost:3001/api
    build:
      context: ./3. Licna dokumenta/frontend
    container_name: mup-licna-dokumenta-frontend
    networks:
      tiseu:
        aliases:
          - mup-licna-dokumenta-frontend
    ports:
      - "3000:3000"
    command: npm start

  mup-licna-dokumenta-backend:
    depends_on:
      - mup-licna-dokumenta-mysql
    build:
      context: ./3. Licna dokumenta/backend/
    container_name: mup-licna-dokumenta-backend
    ports:
      - "3002:3002"
    networks:
      tiseu:
        aliases:
          - mup-licna-dokumenta-backend
    environment:
      - MYSQL_USER=root
      - AUTH_SERVER_API=http://auth-app:3101
      - MYSQL_PASSWORD=root
      - MYSQL_DB=muplicnadokumentadb
      - MYSQL_HOST=mup-licna-dokumenta-mysql
      - MYSQL_PORT=3003

  mup-licna-dokumenta-mysql:
    image: mysql:8.0.23
    container_name: mup-licna-dokumenta-mysql
    ports:
      - "3003:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=muplicnadokumentadb
      - MYSQL_ROOT_HOST=%
    volumes:
      - mup-licna-dokumenta-mysql:/var/lib/mysql
      - ./3. Licna dokumenta/database:/tmp/database
    command: mysqld --init-file="/tmp/database/init_db.sql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      tiseu:
        aliases:
          - "mup-licna-dokumenta-mysql"

volumes:
  auth-mongodb:
    driver: local
  mup-licna-dokumenta-mysql:
    driver: local
